M0IM/BE

- .github/workflows/aws.yml
- .gitignore
- deploy.yml 파일 추가
Close #6 
- deploy 오류 해결
34fa75745cc09af51a6d756e7440f3aa27c1cc5c
- deploy.yml 추가
> :bug: Fix: yml 파일 오류

- .github/workflows/aws.yml
- Dockerfile
Close # 6
- 환경 변수 추가
50c14a60c733356d11c35affdc0b69fcd30cf042
- 환경 변수 추가
> 🐛 Fix: 환경 변수 추가

- .github/workflows/aws.yml
- Dockerfile
Close #6 
- dockerfile 수정 
- Dockerfile 수정
> 🐛 Fix: Dockerfile 수정

- src/main/java/com/dev/moim/domain/account/controller/AuthController.java
- src/main/java/com/dev/moim/domain/account/controller/UserController.java
- src/main/java/com/dev/moim/domain/account/dto/AppleAuthRequest.java
- src/main/java/com/dev/moim/domain/account/dto/AuthRequest.java
- src/main/java/com/dev/moim/domain/account/dto/ReissueTokenResponse.java
- src/main/java/com/dev/moim/domain/account/dto/SignInRequest.java
- src/main/java/com/dev/moim/domain/account/dto/SignUpRequest.java
- src/main/java/com/dev/moim/domain/account/dto/SignUpResponse.java
- src/main/java/com/dev/moim/domain/account/dto/TokenResponse.java
- src/main/java/com/dev/moim/domain/moim/CalenderCreateRequest.java
- src/main/java/com/dev/moim/domain/moim/CalenderCreateResponse.java
- src/main/java/com/dev/moim/domain/moim/CalenderDetailGetResponse.java
- src/main/java/com/dev/moim/domain/moim/CalenderGetResponse.java
- src/main/java/com/dev/moim/domain/moim/CalenderSchedule.java
- src/main/java/com/dev/moim/domain/moim/CalenderUpdateResponse.java
- src/main/java/com/dev/moim/domain/moim/ParticipantProfile.java
- src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
- src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
- src/main/java/com/dev/moim/domain/moim/controller/MoimPostController.java
- src/main/java/com/dev/moim/domain/user/controller/UserController.java
- src/main/java/com/dev/moim/domain/user/dto/ProfileDetailGetResponse.java
- src/main/java/com/dev/moim/domain/user/dto/ProfileListGetResponse.java
- src/main/java/com/dev/moim/domain/user/dto/ProfileResponse.java
- src/main/java/com/dev/moim/domain/user/dto/ProfileUpdateRequest.java
- src/main/java/com/dev/moim/domain/user/dto/receivedReview.java
- src/main/java/com/dev/moim/global/common/BaseResponse.java
- src/main/java/com/dev/moim/global/error/ExceptionAdvice.java
Close #14
- Api 명세서 작성
7ba9e98083d1e4ed86af1275117a1fa3ba6c45d9
- swagger 작성
> 📝 Docs: Api 명세서 작성

- src/main/java/com/dev/moim/global/config/WebConfig.java
Close #16 
- swagger 에러
06a4f6ef3547fb3b09f166bcd7050b7338eb608d
- cors 에러 해결
> 🐛 Fix: swagger 에러

- .github/workflows/aws.yml
- docker image pull fix
Close #16 
- aws.yml 교체
a11b122ec99c658082a5b9e0a2bf236d10f640ae
- aws.yml 교체
> :bug: Fix: aws.yml 교체

- .github/workflows/aws.yml
Close #16 
- docker image 중복 해결
81a5691f21be248f494d2d897b80442282575f5e
- latest 제거
> 🐛 Fix: docker image 중복 해결

- .github/workflows/aws.yml
Close #25 
- docker에 남아있는 이미지 삭제
6a2b0f75b55916f35990e09305667e8c74206280
- git actions에서 기존 docker 이미지 삭제 추가
> :sparkles: Feature: docker image 관리

- src/main/java/com/dev/moim/domain/account/controller/AuthController.java
- src/main/java/com/dev/moim/domain/account/dto/JoinRequest.java
- src/main/java/com/dev/moim/domain/account/entity/User.java
- src/main/java/com/dev/moim/domain/account/entity/UserProfile.java
Close #28 
- User, UserProfile 엔티티 수정
- Swagger 설정
**- User, UserProfile 엔티티 수정**
문자열 값 에러 수정
**- Swagger 설정**
회원가입 요청 DTO에서 role, gender 기본값 및 설명 추가
> 🐛 Fix: 유저 엔티티 문자열 값 설정 수정

- .github/workflows/aws.yml
Close #30 
- RDS private 사용을 위해 -x test 추가
0b76f9beea1ac5d54c806945fae6425db85e4b58
-x test 추가
> MM-18 chore: github actions 수정

- src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
- src/main/java/com/dev/moim/domain/moim/entity/Plan.java
- src/main/java/com/dev/moim/domain/moim/entity/Schedule.java
- src/main/java/com/dev/moim/domain/moim/entity/UserMoim.java
Close #35 
- 캘린더 관련 네이밍 변경
- 일정 엔티티명 변경 (Calender -> Plan)
- 캘린더 컨트롤러 내부 일정 관련 메서드명 변경 (Calender -> Plan)
> ♻ Refactor: 캘린더 관련 네이밍 변경

- build.gradle
- src/main/java/com/dev/moim/domain/account/controller/AuthController.java
- src/main/java/com/dev/moim/domain/account/dto/EmailVerificationCodeDTO.java
- src/main/java/com/dev/moim/domain/account/dto/EmailVerificationResultDTO.java
- src/main/java/com/dev/moim/domain/account/service/AuthService.java
- src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
- src/main/java/com/dev/moim/global/email/EmailConfig.java
- src/main/java/com/dev/moim/global/email/EmailUtil.java
- src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
Close #44 
- 이메일 인증 기능 구현
✔️ 325c65ce974c4602a28bf513befa6cdce2563fc3 : 이메일 인증 기능 구현
- 일반 로그인 타입 회원가입 과정과 비밀번호 변경에서 유저 인증을 위해 사용되는 이메일 인증 기능을 구현했습니다.
> ✨ Feature: 이메일 인증 기능 구현

- build.gradle
Close #49 
- build.gradle 수정
4c1b0bb53740c8db433a9e432ac0bbbb00c4f48b
build.gradle 수정
> 🐛 Fix: build.gradle 수정

- src/main/java/com/dev/moim/domain/account/controller/AuthController.java
- src/main/java/com/dev/moim/domain/account/dto/JoinRequest.java
- src/main/java/com/dev/moim/domain/account/dto/OAuthLoginRequest.java
- src/main/java/com/dev/moim/domain/account/entity/UserProfile.java
- src/main/java/com/dev/moim/domain/account/service/AuthService.java
- src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
- src/main/java/com/dev/moim/global/security/dto/NaverUserInfo.java
- src/main/java/com/dev/moim/global/security/feign/config/GoogleFeignConfiguration.java
- src/main/java/com/dev/moim/global/security/feign/config/KakaoFeignConfiguration.java
- src/main/java/com/dev/moim/global/security/feign/config/NaverFeignConfiguration.java
- src/main/java/com/dev/moim/global/security/feign/decoder/FeignErrorDecoder.java
- src/main/java/com/dev/moim/global/security/feign/request/NaverFeign.java
- src/main/java/com/dev/moim/global/security/filter/CustomLoginFilter.java
- src/main/java/com/dev/moim/global/security/filter/OAuthLoginFilter.java
- src/main/java/com/dev/moim/global/security/service/NaverLoginService.java
- src/main/java/com/dev/moim/global/security/util/NaverLoginAuthenticationProvider.java
- src/main/java/com/dev/moim/global/security/util/NaverLoginAuthenticationToken.java
- src/main/java/com/dev/moim/global/security/util/OIDCAuthenticationProvider.java
- src/main/java/com/dev/moim/global/security/util/OIDCAuthenticationToken.java
Close #46 
- 네이버 로그인 구현
✔️ 2748b84ccc0dc42083961c21f2b874f95d794cf0 : 네이버 소셜 로그인 기능 구현
> ✨ Feature: 네이버 소셜 로그인 기능 구현

- src/main/java/com/dev/moim/global/config/SwaggerConfig.java
Close #56 
- swagger https url 허용
9887c48f7e302bc0ab1eec865d63756dd8c17dcf
- swagger https url 허용
> 🐛 Fix: swagger https url 허용

- src/main/java/com/dev/moim/domain/account/controller/AuthController.java
- src/main/java/com/dev/moim/domain/account/dto/EmailDTO.java
- src/main/java/com/dev/moim/domain/account/dto/TokenResponse.java
- src/main/java/com/dev/moim/domain/account/entity/enums/Provider.java
- src/main/java/com/dev/moim/domain/account/service/AuthService.java
- src/main/java/com/dev/moim/global/redis/util/RedisUtil.java
- src/main/java/com/dev/moim/global/security/filter/CustomLoginFilter.java
- src/main/java/com/dev/moim/global/security/filter/OAuthLoginFilter.java
- src/main/resources/application.yml
> ♻️ Refactor: 회원가입 DTO 수정

- src/main/java/com/dev/moim/domain/user/UserService.java
- src/main/java/com/dev/moim/domain/user/controller/UserController.java
- src/main/java/com/dev/moim/domain/user/dto/ProfileDTO.java
- src/main/java/com/dev/moim/global/security/annotation/AuthUserArgumentResolver.java
Close #60
- 유저 프로필 조회 기능 구현
- 프론트 개발자분의 요청이 있어서 유저의 기본 정보를 조회하는 API를 구현했습니다. 기획이 확정되고 나면, 필요한 데이터들을 추가해서 필드를 수정할 계획입니다.
✔️ eff0ae5c1bdc863a0c6525d4a6e1422aa1cabecc : 유저 프로필 조회
✔️ ccbc15b87f4c5727b09e6d15b56824fe8cd27999 : @AuthUser이용한 유저 정보 추출
> ✨ Feat: 유저 프로필 조회 기능 구현

- src/main/java/com/dev/moim/domain/account/controller/AuthController.java
- src/main/java/com/dev/moim/domain/account/entity/User.java
- src/main/java/com/dev/moim/domain/account/service/AuthService.java
Close #65 
- providerId 컬럼 길이 제한으로 인한 에러
✔️ 26f0618ef8c70f4a5713dd2b65dc106d6670c452 : providerId 컬럼 @Lob 설정
> 🐛 Fix: providerId 컬럼 길이 제한으로 인한 에러

- src/main/java/com/dev/moim/domain/account/controller/AuthController.java
- src/main/java/com/dev/moim/domain/account/entity/User.java
- src/main/java/com/dev/moim/domain/account/service/AuthService.java
- src/main/java/com/dev/moim/global/error/ExceptionAdvice.java
- src/main/java/com/dev/moim/global/error/feign/dto/DiscordMessage.java
- src/main/java/com/dev/moim/global/error/feign/service/DiscordClient.java
- src/main/resources/application-discord.yml
- src/main/resources/application.yml
Close #68 
- error discord 전송 기능
76be098da8d093a9eeb57c4442a64ba69a381305
error discord 전송 기능
> ✨ Feat: error send to discord

- build.gradle
- src/main/java/com/dev/moim/global/s3/S3Config.java
- src/main/java/com/dev/moim/global/s3/controller/S3Controller.java
- src/main/java/com/dev/moim/global/s3/dto/AwsDTO.java
- src/main/java/com/dev/moim/global/s3/service/S3Service.java
- src/main/resources/application-s3.yml
- src/main/resources/application.yml
Close #82 
-  presigned url 생성
> ✨ Feature: presigned url 생성

- src/main/java/com/dev/moim/global/s3/controller/S3Controller.java
- src/main/java/com/dev/moim/global/s3/dto/AwsDTO.java
- src/main/java/com/dev/moim/global/s3/service/S3Service.java
Close #84 
- resigned url list 추가
2c2c15b4b747a33e35b8e6580d5a1a0911bf7ba8
- presigned url list 추가
> ✨ Feature: presigned url list 추가

- src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
- src/main/java/com/dev/moim/domain/moim/controller/enums/MoimRequestType.java
- src/main/java/com/dev/moim/domain/moim/dto/CreateMoimDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/CreateMoimResultDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/MoimPreviewDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/MoimPreviewListDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/UpdateMoimDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/WithMoimDTO.java
- src/main/java/com/dev/moim/domain/moim/entity/Moim.java
- src/main/java/com/dev/moim/domain/moim/entity/MoimImage.java
- src/main/java/com/dev/moim/domain/moim/entity/enums/MoimCategory.java
- src/main/java/com/dev/moim/domain/moim/repository/ExitReasonRepository.java
- src/main/java/com/dev/moim/domain/moim/repository/MoimImageRepository.java
- src/main/java/com/dev/moim/domain/moim/repository/MoimRepository.java
- src/main/java/com/dev/moim/domain/moim/service/MoimCommandService.java
- src/main/java/com/dev/moim/domain/moim/service/MoimQueryService.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/PostQueryServiceImpl.java
Close #87 
- 모임 crud 기능 구현
45efd0b1efb3f104f8227ad6242777eb99697fff
39f499b1b9a5936a06887fa2970263ec1bcb57de
0558df7a2b00c1712994315a24297c3c40b29caf
4154a5d00cd6bf346dd844d81faaa58862c66e32
fe0a8b2598e6ec80e20840f129e561ee0f4d5377
- 모임 crud 기능 구현
> ✨ Feature : 모임 crud 기능 구현

- src/main/java/com/dev/moim/domain/user/controller/UserController.java
- src/main/java/com/dev/moim/domain/user/dto/ReviewListDTO.java
- src/main/java/com/dev/moim/domain/user/service/UserService.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserServiceImpl.java
Close #98
- 유저 후기 조회 수정
✔️ cede96cd38b8e6fb54f813ffc90c0b8d0486752a : 유저 후기 리스트 조회 수정 
- 다른 멤버 후기 조회, 내 후기 조회 API 통일
- 후기 조회 응답 수정
> 🐛 Fix: 유저 후기 조회 수정

- src/main/java/com/dev/moim/global/s3/controller/S3Controller.java
- src/main/java/com/dev/moim/global/s3/dto/AwsDTO.java
- src/main/java/com/dev/moim/global/s3/service/S3Service.java
Close #96 
- 리스트용 presigned url 설정
7a6d8991d5d8abf0238b66e0bdd5805c8d32c551
- 리스트용 presigned url 설정
> ✨ Feature : 리스트용 presigned url 설정

- src/main/java/com/dev/moim/domain/account/entity/User.java
- src/main/java/com/dev/moim/domain/account/entity/UserProfile.java
- src/main/java/com/dev/moim/domain/account/entity/UserReview.java
- src/main/java/com/dev/moim/domain/account/repository/UserReviewRepository.java
- src/main/java/com/dev/moim/domain/moim/dto/post/CommentCommentResponseDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/post/CommentResponseDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/post/MoimPostDetailDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/post/MoimPostPreviewDTO.java
- src/main/java/com/dev/moim/domain/user/controller/UserController.java
- src/main/java/com/dev/moim/domain/user/dto/CreateReviewDTO.java
- src/main/java/com/dev/moim/domain/user/dto/CreateReviewResultDTO.java
- src/main/java/com/dev/moim/domain/user/dto/ProfileDTO.java
- src/main/java/com/dev/moim/domain/user/dto/ProfileDetailDTO.java
- src/main/java/com/dev/moim/domain/user/dto/ReviewDTO.java
- src/main/java/com/dev/moim/domain/user/dto/UpdateUserInfoDTO.java
- src/main/java/com/dev/moim/domain/user/service/UserCommandService.java
- src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Close #102 
- 유저 정보 조회 기능 추가
✔️ 97c2a920d49917ed5c8856b0f39b499d92b35e0e : 프로필 상세 조회 API 분리
✔️ ad481f84a8a6e3828e1948866fec18665d79fade : 유저 후기 리스트 조회 API 분리
✔️ 7858363821e21989bf1c8ceabeb8a14ca560a390 : 멤버 리뷰 작성 기능 구현
✔️ 6ed3937c9a11f95b3bb8a0312bf71a8fdc2a30d0 : UserService명 변경
✔️ 93a76a9d6cb79d937bb8f1b4f410a0b838bab678 : nickname으로 통일
✔️ 4fb9f3df21d403adf48fbeb4ab16a82cac0067ed : image 네이밍 정리
✔️ 13ab1f6f02b3c713e31a3dce37f5b80a0bd5fa07
- imgaeUrl을 저장하는 방식으로 정하면서 이미지 관련 네이밍을 정리했습니다
프론트 측에서 imageKey를 받아오면, imageUrl을 받아와서 저장하는 로직도 이후 추가하겠습니다.
> ✨ Feature: 유저 정보 조회 기능 추가

- src/main/java/com/dev/moim/domain/moim/dto/MoimIntroduceDTO.java
- src/main/java/com/dev/moim/domain/user/dto/UserPreviewDTO.java
Close #104 
- 이미지 네이밍 에러 해결
이미지 네이밍 관련 에러 해결했습니다.
> 🐛 Fix: 이미지 네이밍 에러 해결

- src/main/java/com/dev/moim/domain/moim/repository/UserPlanRepository.java
- src/main/java/com/dev/moim/domain/moim/service/impl/CalenderQueryServiceImpl.java
Close #88
- 모임 일정 참여자 조회 쿼리 성능 개선
✔️ a5e9f7bb3314d75402640c1cae54b53e1e34bf66 : 모임 일정 참여자 조회 쿼리 성능 개선
> ♻️ Refactor: 모임 일정 참여자 조회 쿼리 성능 개선

- src/main/java/com/dev/moim/domain/account/entity/User.java
- src/main/java/com/dev/moim/domain/user/controller/UserController.java
- src/main/java/com/dev/moim/domain/user/dto/AlarmDTO.java
- src/main/java/com/dev/moim/domain/user/service/UserCommandService.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserCommandServiceImpl.java
Close #93 
- 알림 설정 관련 api
77c3b4c20c6442643bab9f2047dc8901f5c99ad1
3f778741b04f8acc7a08c08f37e27248beec2dac
- 알림 설정 관련 api
> ✨ Feature: 알림 설정 관련 api

- src/main/java/com/dev/moim/domain/moim/dto/CreateMoimDTO.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
Close #108 
- 모임 관련 api 수정
81122074d58614939e9acf8ae47823d899d01533
- 모임 관련 api 수정
> ♻️ Refactor : 모임 관련 api 수정

- src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
- src/main/java/com/dev/moim/domain/moim/repository/MoimRepository.java
- src/main/java/com/dev/moim/domain/moim/service/MoimQueryService.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
Close #92 
- 신규 모임 조회
addaeeec3071a523aec34ba0d152c081e2abb2ee
- 신규 모임 조회
> ✨  Feature : 신규 모임 조회

- src/main/java/com/dev/moim/domain/moim/controller/MoimPostController.java
Close #109 
- 좋아요 url 수정
2bee0506341c11ccb57c7ff95b90ee481140380a
- 좋아요 url 수정
> ♻️ Refactor : 좋아요 url 수정

- src/main/java/com/dev/moim/domain/account/entity/UserProfile.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserCommandServiceImpl.java
- src/main/java/com/dev/moim/global/s3/controller/S3Controller.java
- src/main/java/com/dev/moim/global/s3/service/S3Service.java
Close #113 
- 이미지 처리 방식 변경
✔️ 7f31004e3abb1da22e237fc88a93d410133567b3 : 이미지 처리 방식 변경
- 기존엔 s3에 이미지 업로드, 다운로드 시 모두 presignedUrl을 이용하는 방식으로 처리하기로 했습니다. 하지만 이 경우 요청이 늘어나고 처리 시간이 길어지므로 프론트 측과 이미지 처리 방식에 대해서 의논하여 정적 url을 저장해두는 방식으로 변경했습니다.
> ♻️ Refactor: 이미지 처리 방식 변경

- src/main/java/com/dev/moim/domain/user/dto/UpdateUserInfoDTO.java
- src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
- src/main/java/com/dev/moim/global/validation/annotation/UserMoimListValidation.java
- src/main/java/com/dev/moim/global/validation/validator/UserMoimListValidator.java
Close #115 
- 모임 id 리스트 검증 커스텀 어노테이션 구현
✔️ 2d92afc80b74b75eaebb97bd6df88b1a94a77169 : 모임 id 리스트 검증 어노테이션 구현
- 유저 정보 수정 시, 유저가 프로필에 공개하는 모임으로 선택한 모임이 유저가 참여하는 모임이 맞는지 검증하는 커스텀 어노테이션을 구현했습니다
- [x ] 변경 내용에 대한 테스트를 진행했어요.
> ✨ Feature: 모임 id 리스트 검증 커스텀 어노테이션 구현

- src/main/java/com/dev/moim/global/s3/dto/AwsDTO.java
- src/main/java/com/dev/moim/global/s3/service/S3Service.java
Close #119 
- 이미지 업로드 presignedUrl DTO 수정
✔️ 991b57354990864c737246c4e4b844fd8e9dcfa4 : 이미지 업로드 presignedUrl DTO 수정
- 이미지 업로드 presignedUrl DTO 필드명 fileName으로 변경
> ✨ Feature: 이미지 업로드 presignedUrl DTO 수정

- src/main/java/com/dev/moim/domain/account/entity/User.java
- src/main/java/com/dev/moim/domain/account/service/AuthService.java
Close #117
- User 엔티티 nickname 삭제
✔️ 0f9a8bae463492179f4f711139ee44cc8f6d8c46 : User 엔티티 nickname 삭제
- 멀티 프로필이 도입될 경우, 프로필마다 닉네임 설정이 가능한 기획에 따라 User 엔티티에서 nickname을 삭제했습니다.
> ✨ Feature: 유저 엔티티 변경

- src/main/java/com/dev/moim/global/s3/dto/AwsDTO.java
- src/main/java/com/dev/moim/global/s3/service/S3Service.java
> ♻️ Refactor: S3 서비스 로직 수정

- src/main/java/com/dev/moim/global/s3/service/S3Service.java
Close #127 
- presigned url 수정
- presigned url 수정
> 🐛 Fix : presigned url 수정

- src/main/java/com/dev/moim/domain/account/entity/User.java
- src/main/java/com/dev/moim/domain/moim/controller/MoimPostController.java
- src/main/java/com/dev/moim/domain/moim/dto/post/PostBlockDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/post/PostReportDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/post/UpdateMoimPostDTO.java
- src/main/java/com/dev/moim/domain/moim/entity/Post.java
- src/main/java/com/dev/moim/domain/moim/entity/PostBlock.java
- src/main/java/com/dev/moim/domain/moim/entity/PostReport.java
- src/main/java/com/dev/moim/domain/moim/repository/PostBlockRepository.java
- src/main/java/com/dev/moim/domain/moim/repository/PostReportRepository.java
- src/main/java/com/dev/moim/domain/moim/repository/PostRepository.java
- src/main/java/com/dev/moim/domain/moim/service/PostCommandService.java
- src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/PostQueryServiceImpl.java
- src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
- src/main/resources/application.yml
Close #126 
- 게시글 관련 api
- 게시글 관련 api
> ✨ Feature : 게시글 관련 api

- src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
- src/main/java/com/dev/moim/domain/moim/controller/enums/MoimRequestType.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
Close #134 
- 모임 조회 관련 수정
- 모임 조회 관련 수정
> ♻️ Refactor : 모임 조회 관련 수정

- src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
> 🐛 Fix: resolve merge conflict

- src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
- src/main/java/com/dev/moim/domain/moim/service/impl/CalenderQueryServiceImpl.java
- src/main/java/com/dev/moim/domain/user/controller/UserController.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
- src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
- src/main/java/com/dev/moim/global/validation/annotation/CheckCursorValidation.java
- src/main/java/com/dev/moim/global/validation/annotation/CheckPageValidation.java
- src/main/java/com/dev/moim/global/validation/annotation/CheckSizeValidation.java
- src/main/java/com/dev/moim/global/validation/validator/CheckCursorValidator.java
- src/main/java/com/dev/moim/global/validation/validator/CheckSizeValidator.java
Close #137 
- page 시작 번호 변경
✔️ ca4f02b0dbda32350891301dc71cb37bb6010d80 : page 검증 어노테이션 구현
✔️ a7284143a7a020579d3f908ceab5995410801fe5 : size 검증 어노테이션 구현
✔️ d40a64c47c96916ed90392027100154d940ebd5e : page, size 검증 어노테이션 적용
✔️ 872ac515d636b578803b3bc2e2dbb4e8134ae44e : page 시작 번호 변경
> ♻️ [Refactor] page 시작 번호 변경

- src/main/java/com/dev/moim/domain/moim/controller/MoimPostController.java
- src/main/java/com/dev/moim/domain/moim/dto/post/CommentBlockDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/post/CommentReportDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/post/CommentResponseDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/post/CommentUpdateRequestDTO.java
- src/main/java/com/dev/moim/domain/moim/entity/Comment.java
- src/main/java/com/dev/moim/domain/moim/entity/CommentBlock.java
- src/main/java/com/dev/moim/domain/moim/entity/CommentReport.java
- src/main/java/com/dev/moim/domain/moim/repository/CommentBlockRepository.java
- src/main/java/com/dev/moim/domain/moim/repository/CommentReportRepository.java
- src/main/java/com/dev/moim/domain/moim/repository/CommentRepository.java
- src/main/java/com/dev/moim/domain/moim/service/PostCommandService.java
- src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/PostQueryServiceImpl.java
- src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
Close #133 
- 댓글 관련 api
- 댓글 관련 api
> ✨ Feature : 댓글 관련 api

- src/main/java/com/dev/moim/domain/account/dto/JoinRequest.java
- src/main/java/com/dev/moim/domain/account/entity/User.java
- src/main/java/com/dev/moim/domain/account/entity/UserProfile.java
- src/main/java/com/dev/moim/domain/account/service/AuthService.java
- src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
- src/main/java/com/dev/moim/domain/moim/dto/MoimDetailDTO.java
- src/main/java/com/dev/moim/domain/moim/repository/PlanRepository.java
- src/main/java/com/dev/moim/domain/moim/repository/PostRepository.java
- src/main/java/com/dev/moim/domain/moim/service/MoimQueryService.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
- src/main/java/com/dev/moim/domain/user/dto/ProfileDetailDTO.java
Close #130 
- 모임 스페이스 조회 api
- 모임 스페이스 조회 api
> ✨ Feature : 모임 스페이스 조회 api

- src/main/java/com/dev/moim/domain/chatting/controller/ChatRoomController.java
- src/main/java/com/dev/moim/domain/chatting/repository/CustomChatRoomRepository.java
- src/main/java/com/dev/moim/domain/chatting/repository/CustomChatRoomRepositoryImpl.java
- src/main/java/com/dev/moim/domain/chatting/service/ChatRoomQueryService.java
- src/main/java/com/dev/moim/domain/chatting/service/impl/ChatRoomQueryServiceImpl.java
Close #144 
- 채팅방 모임id 수정
-채팅방 모임id 수정
> ♻️ Refactor : 채팅방 모임id 수정

- src/main/java/com/dev/moim/domain/chatting/controller/ChatRoomController.java
- src/main/java/com/dev/moim/domain/chatting/converter/ChatConverter.java
- src/main/java/com/dev/moim/domain/chatting/converter/ChatRoomConverter.java
- src/main/java/com/dev/moim/domain/chatting/dto/ChatRoomDTO.java
- src/main/java/com/dev/moim/domain/chatting/entity/Chat.java
- src/main/java/com/dev/moim/domain/chatting/entity/ChatRoom.java
- src/main/java/com/dev/moim/domain/chatting/service/impl/ChatQueryServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
- src/main/java/com/dev/moim/global/socket/dto/ChattingDTO.java
- src/main/java/com/dev/moim/global/socket/service/SocketService.java
- src/main/java/com/dev/moim/global/validation/annotation/CheckChatRoomValidation.java
Close #145 
- 사진 api 변환
- 사진 api 변환
> ♻️ Refactor : 사진 api 변환

- src/main/java/com/dev/moim/domain/account/dto/JoinRequest.java
- src/main/java/com/dev/moim/domain/moim/dto/calender/PlanCreateDTO.java
- src/main/java/com/dev/moim/domain/moim/service/impl/CalenderCommandServiceImpl.java
Close #147
- 날짜, 시간 타입 변경
✔️ 5043736b35cd414d0e7a185b9564dbcadde0a032 : 회원가입 DTO birth @JsonFormat 추가
✔️ 812dfa7d74140442fd47674e0c5828436307f977 : 모임 일정 DTO 날짜, 시간 타입 변경
- 날짜 LocalDate
- 시작 시간 LocalTime
> ♻️ Refactor: 날짜, 시간 타입 변경

- src/main/java/com/dev/moim/domain/account/controller/AuthController.java
- src/main/java/com/dev/moim/domain/account/dto/JoinRequest.java
- src/main/java/com/dev/moim/domain/account/dto/UpdatePasswordDTO.java
- src/main/java/com/dev/moim/domain/account/entity/User.java
- src/main/java/com/dev/moim/domain/account/entity/UserProfile.java
- src/main/java/com/dev/moim/domain/account/service/AuthService.java
- src/main/java/com/dev/moim/domain/moim/entity/UserMoim.java
- src/main/java/com/dev/moim/domain/moim/entity/enums/JoinStatus.java
- src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
- src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
- src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
- src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
- src/main/java/com/dev/moim/global/validation/annotation/ExistEmailValidation.java
- src/main/java/com/dev/moim/global/validation/annotation/JoinPasswordValidation.java
- src/main/java/com/dev/moim/global/validation/annotation/QuitValidation.java
- src/main/java/com/dev/moim/global/validation/annotation/UpdatePasswordValidation.java
- src/main/java/com/dev/moim/global/validation/validator/ExistEmailValidator.java
- src/main/java/com/dev/moim/global/validation/validator/JoinPasswordValidator.java
- src/main/java/com/dev/moim/global/validation/validator/QuitValidator.java
- src/main/java/com/dev/moim/global/validation/validator/UpdatePasswordValidator.java
Close #151
- 유저 관련 기능 추가
✔️ cd5112cdb1a134fc1a6161d24a82513c7b1f7f77 : 회원 탈퇴 기능 구현
- User, UserMoim, UserProfile soft delete
✔️ adaeb782ce15478afec80e39dbfe1df776b6f81e : 비밀번호 변경 기능 구현
- 비밀번호 유효성 검사 어노테이션 추가 (join, update 분리)
✔️ 3671189353b1fa57b65b9437199619141010a2cc : 회원 탈퇴 기능 구현
- 모임장 권한이 있는 유저는 회원 탈퇴 전에 모임장 권한 위임을 진행하도록, 모임장 권한이 있는지 여부 확인하는 로직 추가
> ✨ Feature: 유저 관련 기능 추가

- src/main/java/com/dev/moim/domain/region/controller/RegionController.java
- src/main/java/com/dev/moim/domain/region/dto/RegionDTO.java
- src/main/java/com/dev/moim/domain/region/dto/RegionListDTO.java
- src/main/java/com/dev/moim/domain/region/entity/Dong.java
- src/main/java/com/dev/moim/domain/region/entity/Sido.java
- src/main/java/com/dev/moim/domain/region/entity/Sigungu.java
- src/main/java/com/dev/moim/domain/region/repository/DongRepository.java
- src/main/java/com/dev/moim/domain/region/repository/SidoRepository.java
- src/main/java/com/dev/moim/domain/region/repository/SigunguRepository.java
- src/main/java/com/dev/moim/domain/region/service/RegionQueryService.java
- src/main/java/com/dev/moim/domain/region/service/impl/RegionQueryServiceImpl.java
- src/main/java/com/dev/moim/global/security/config/SecurityConfig.java
Close #160 
- 행정구역 조회 API 구현
✔️ 7cf049bc64ca96586752992d1aec4454b9fdc9e8 : 행정구역 조회 기능 구현
- 회원가입 절차 중 지역 선택 부분에 사용될 행정구역 조회 기능입니다
> ✨ Feature: 행정구역 조회 API 구현

- src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
- src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
- src/main/java/com/dev/moim/domain/moim/dto/ChangeMoimLeaderRequestDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/MoimJoinConfirmRequestDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/MoimJoinRequestDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/MoimJoinRequestListDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/post/CommentResponseDTO.java
- src/main/java/com/dev/moim/domain/moim/entity/UserMoim.java
- src/main/java/com/dev/moim/domain/moim/repository/MoimRepository.java
- src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
- src/main/java/com/dev/moim/domain/moim/service/MoimCommandService.java
- src/main/java/com/dev/moim/domain/moim/service/MoimQueryService.java
- src/main/java/com/dev/moim/domain/moim/service/impl/CalenderQueryServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/dto/JoinRequestDTO.java
- src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
- src/main/java/com/dev/moim/global/validation/validator/CheckAdminValidator.java
Close #152 
- 모임관련 기능 api
- 모임관련 기능 api
> ✨ Feature: 모임관련 기능 api

- src/main/java/com/dev/moim/domain/account/repository/AlarmRepository.java
- src/main/java/com/dev/moim/domain/user/controller/UserController.java
- src/main/java/com/dev/moim/domain/user/service/UserCommandService.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserCommandServiceImpl.java
Close #153 
- 알림 삭제 기능
- 알림 삭제 기능
> ✨ Feature : 알림 삭제 기능

- .platform/nginx.conf
Close #165 
- 웹소켓 타임아웃 늘리기
- 웹소켓 타임아웃 늘리기
> ♻️ Refactor : 웹소켓 타임아웃 늘리기

- src/main/java/com/dev/moim/global/socket/handler/TextHandler.java
Close #165 
- 웹소켓 로그 출력
- 웹소켓 로그 출력
> ♻️ Refactor: 웹소켓 로그 출력

- .platform/nginx.conf
Close #169 
- 타임 아웃 늘리기
- 타임 아웃 늘리기
> ♻️ Refactor: 타임 아웃 늘리기

- src/main/java/com/dev/moim/domain/account/repository/UserProfileRepository.java
- src/main/java/com/dev/moim/domain/moim/dto/MoimDetailDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/UpdateMoimDTO.java
- src/main/java/com/dev/moim/domain/moim/entity/Moim.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
> ♻️ Refactor: 모임 수정

- src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
- src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
- src/main/java/com/dev/moim/global/validation/validator/UserMoimValidator.java
- src/main/java/com/dev/moim/global/validation/validator/UserPlanValidator.java
Close #174 
- 모임 수정 권한 검증 어노테이션 버그 해결
✔️ 9d0f80f199bae648846f417954d5e94f40990685 : 모임 일정 수정 권한 검증 어노테이션 버그 해결
✔️ f63b405b41d2c4e5948b6731bc402ab295442a61 : 모임, 일정 검증 로직에 어노테이션 적용
- controller 파라미터에 어노테이션을 2개 적용해서 원하는 우선 순위대로 동작하지 않았고, 어노테이션 파라미터 안에 다른 어노테이션을 적용하는 형태로 변경했습니다
> 🐛 Fix: 모임 일정 수정 권한 검증 어노테이션 수정

- src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
Close #177 
- 공지사항 문자열 수정
- 공지사항 문자열 수정
> 🐛 Fix: 공지사항 문자열 수정

- src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
Close #180 
- 공지 사항 리턴 문자열 수정
- 공지 사항 리턴 문자열 수정
> ♻️ Refactor : 공지 사항 리턴 문자열 수정

- .ebextensions-dev/02-nginx-timeout.config
- .platform/nginx.conf
Close #189 
- 웹소켓 시간 늘리기
- 웹소켓 시간 늘리기
> ♻️ Refactor: 웹소켓 시간 늘리기

- .ebextensions-dev/02-nginx-timeout.config
> MM-164 refactor : 웹소켓 문서 추가

- src/main/java/com/dev/moim/domain/user/dto/AlarmResponseDTO.java
Close #187 
- 알림 목록 조회 시 생성 시간 추가
- 알림 목록 조회 시 생성 시간 추가
> ♻️ Refactor: 알림 목록 조회 시 생성 시간 추가

- src/main/java/com/dev/moim/global/security/filter/CustomLoginFilter.java
- src/main/java/com/dev/moim/global/security/filter/OAuthLoginFilter.java
- src/main/java/com/dev/moim/global/validation/validator/FcmTokenValidator.java
Close #193 
- fcmToken 빈문자열 처리
> 🐛 Fix: fcmToken 빈문자열 처리

- src/main/java/com/dev/moim/domain/user/dto/ProfileDTO.java
Close #202
- 유저 프로필 정보 조회 DTO에 provider 추가
✔️ 860e37f6f7cb3e9611067e7fc7cdfc2b61e155f5 : 유저 프로필 정보 조회 DTO에 provider 추가
> ✨ Feature: 유저 프로필 정보 조회 DTO에 provider 추가

- src/main/java/com/dev/moim/domain/region/controller/RegionController.java
- src/main/java/com/dev/moim/domain/region/dto/RegionSearchDTO.java
- src/main/java/com/dev/moim/domain/region/dto/RegionSearchListDTO.java
- src/main/java/com/dev/moim/domain/region/repository/DongRepository.java
- src/main/java/com/dev/moim/domain/region/service/RegionQueryService.java
- src/main/java/com/dev/moim/domain/region/service/impl/RegionQueryServiceImpl.java
Close #205 
- 행정구역 검색 기능 구현
✔️ a35ba38a6883248b8b6e76f50cb46106a656c277 : 행정구역 검색 기능 구현
> ✨ Feature: 행정구역 검색 기능 구현

- src/main/java/com/dev/moim/domain/account/dto/JoinRequest.java
- src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
- src/main/java/com/dev/moim/global/security/filter/CustomLoginFilter.java
- src/main/java/com/dev/moim/global/security/filter/OAuthLoginFilter.java
- src/main/java/com/dev/moim/global/validation/validator/UserMoimValidator.java
Close #207
- 모임 일정 접근 권한 설정
✔️ 9bb3bff391faf2f884a373cd08d9f81f77cbab10 : fcmToken 유효성 검증 로직 제거
- 개발 진행을 위해 로그인, 회원가입 로직에 적용되어있던 fcmToken 유효성 검증 적용을 제외시켰습니다
✔️ 81c6596c022332a818cd6854f83c45951e65a5dc : 모임 참여 유저인지 검증하는 어노테이션 조건 추가
- join_status가 COMPLETE인 유저만 모임에 참여하는 유저로 적용시키기 위해서 조회 조건을 추가했습니다
> ✨ Feature: 모임 일정 접근 권한 설정

- src/main/java/com/dev/moim/domain/moim/dto/post/MoimPostPreviewDTO.java
Close #211 
- 모임 소개 게시물 조회 DTO 모임 이미지 추가
✔️ 3c7c1d8178e258ec4e87f799858dec2b0a720924 : 모임 소개 게시물 조회 DTO 모임 이미지 추가
> ✨ Feature: 모임 소개 게시물 조회 DTO 모임 이미지 추가

- src/main/java/com/dev/moim/domain/moim/dto/post/MoimPostPreviewDTO.java
Close #213 
- 모임 소개 게시물 조회 DTO 모임 커버 이미지로 변경
✔️ 4604a0e5ca50f579fda8208c736bfacb34fae990 : 모임 소개 게시물 조회 DTO 모임 커버 이미지로 변경
> ✨ Feature: 모임 소개 게시물 조회 DTO 모임 커버 이미지로 변경

- src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
- src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
- src/main/java/com/dev/moim/domain/moim/controller/MoimPostController.java
- src/main/java/com/dev/moim/domain/moim/dto/MoimDetailDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/MoimJoinRequestDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/post/AnnouncementConfirmRequestDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/post/AnnouncementRequestDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/post/BlockCommentResponse.java
- src/main/java/com/dev/moim/domain/moim/dto/post/JoinMoimPostsResponseDTO.java
- src/main/java/com/dev/moim/domain/moim/entity/Post.java
- src/main/java/com/dev/moim/domain/moim/entity/ReadPost.java
- src/main/java/com/dev/moim/domain/moim/repository/CommentRepository.java
- src/main/java/com/dev/moim/domain/moim/repository/PostRepository.java
- src/main/java/com/dev/moim/domain/moim/repository/ReadPostRepository.java
- src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
- src/main/java/com/dev/moim/domain/moim/service/MoimQueryService.java
- src/main/java/com/dev/moim/domain/moim/service/PostCommandService.java
- src/main/java/com/dev/moim/domain/moim/service/PostQueryService.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/PostQueryServiceImpl.java
- src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Close #210 
- 모임 관련 api 수정
- 모임 관련 api 수정
> ♻️ Refactor: 모임 관련 api 수정

- src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
> MM-181 fix: 여러개 조회 수정

- src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
- src/main/java/com/dev/moim/domain/moim/controller/MoimPostController.java
- src/main/java/com/dev/moim/domain/moim/converter/PostConverter.java
- src/main/java/com/dev/moim/domain/moim/dto/post/CommentCommentResponseDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/post/CommentResponseDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/post/MoimPostDetailDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/post/MoimPostPreviewDTO.java
- src/main/java/com/dev/moim/domain/moim/entity/UserMoim.java
- src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
- src/main/java/com/dev/moim/domain/moim/service/impl/PostQueryServiceImpl.java
Close #222 
- 모임 관련 버그 해결
- 모임 관련 버그 해결
> 🐛 Fix: 모임 관련 버그 해결

- src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
- src/main/java/com/dev/moim/domain/moim/service/CalenderQueryService.java
- src/main/java/com/dev/moim/domain/moim/service/impl/CalenderQueryServiceImpl.java
- src/main/java/com/dev/moim/domain/user/controller/UserController.java
- src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Close #221 
- 유저 일정 상세 조회 기능 구현
✔️ cc0f1c2ce7c6ec3da98f29c265c20effcf72534a : 유저 일정 상세 조회 기능 구현
- 유저 개인 일정 상세 조회
- 유저가 참여 신청한 모임 일정 상세 조회
> ✨ Feature 유저 일정 상세 조회 기능 구현

- src/main/java/com/dev/moim/domain/moim/repository/MoimRepository.java
- src/main/java/com/dev/moim/domain/moim/service/CalenderQueryService.java
- src/main/java/com/dev/moim/domain/moim/service/MoimQueryService.java
- src/main/java/com/dev/moim/domain/moim/service/impl/CalenderQueryServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
- src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
- src/main/java/com/dev/moim/global/validation/annotation/MoimValidation.java
- src/main/java/com/dev/moim/global/validation/annotation/PlanValidation.java
- src/main/java/com/dev/moim/global/validation/validator/ExistUserValidator.java
- src/main/java/com/dev/moim/global/validation/validator/LocalAccountValidator.java
- src/main/java/com/dev/moim/global/validation/validator/MoimValidator.java
- src/main/java/com/dev/moim/global/validation/validator/OAuthAccountValidator.java
- src/main/java/com/dev/moim/global/validation/validator/PlanAuthorityValidator.java
- src/main/java/com/dev/moim/global/validation/validator/PlanValidator.java
- src/main/java/com/dev/moim/global/validation/validator/SelfReviewValidator.java
- src/main/java/com/dev/moim/global/validation/validator/UserMoimValidator.java
- src/main/java/com/dev/moim/global/validation/validator/UserPlanDuplicateValidator.java
- src/main/java/com/dev/moim/global/validation/validator/UserPlanValidator.java
> ♻️ Refactor: 커스텀 어노테이션 정리

- src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
- src/main/java/com/dev/moim/domain/moim/repository/MoimRepository.java
- src/main/java/com/dev/moim/domain/moim/service/MoimQueryService.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
Close #208 
- 다른 유저의 참여 모임 조회 기능 구현
✔️ 7b91f9ee34f36ecd2f361e787610900f053e83a7 : 다른 유저의 참여 모임 조회 기능 구현
> ✨ Feature: 다른 유저의 참여 모임 조회 기능 구현

- src/main/java/com/dev/moim/domain/moim/repository/PlanRepository.java
Close #231
- 특정 날짜 유저의 모든 예정된 일정 조회 쿼리 수정
✔️ 5e135761a0d39ab38c03fa75151add88446d584a : 특정 날짜 유저의 모든 예정된 일정 조회 쿼리 수정
> 🐛 Fix: 특정 날짜 유저의 모든 예정된 일정 조회 쿼리 수정

- src/main/java/com/dev/moim/domain/moim/entity/Plan.java
Close #233 
- plan 엔티티 schedule 업데이트 로직 수정
✔️ 89a21396b2bac8080baca759526f2fb95a1aa953 : plan 엔티티 schedule 업데이트 로직 수정
> ✨ Feature: plan 엔티티 schedule 업데이트 로직 수정

- src/main/java/com/dev/moim/domain/account/entity/User.java
Close #229 
- 초기 값 true로 변경
- 초기 값 true로 변경
> ♻️ Refactor: 초기 값 true로 변경

- src/main/java/com/dev/moim/domain/account/entity/Alarm.java
- src/main/java/com/dev/moim/domain/account/entity/User.java
- src/main/java/com/dev/moim/domain/account/entity/enums/AlarmDetailType.java
- src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
- src/main/java/com/dev/moim/domain/account/service/AlarmCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/account/service/AlarmService.java
- src/main/java/com/dev/moim/domain/account/service/AuthService.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/user/controller/AlarmController.java
- src/main/java/com/dev/moim/domain/user/dto/AlarmCountResponseDTO.java
- src/main/java/com/dev/moim/domain/user/dto/AlarmResponseDTO.java
- src/main/java/com/dev/moim/domain/user/service/UserCommandService.java
- src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
- src/main/java/com/dev/moim/global/firebase/service/FcmService.java
- src/main/java/com/dev/moim/global/socket/service/SocketService.java
Close #235 
- 알림 관련 수정 API
- 알림 관련 수정 API
> ♻️ Refactor: 알림 관련 수정 API

- src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
- src/main/java/com/dev/moim/domain/user/dto/ProfileDetailDTO.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Close #239 
- 유저 프로필 상세 조회 DTO 가입된 모임 수 추가
✔️ dd82e7c6f7593a4ac1db6c8a29b9d8df12245eaa : 유저 프로필 상세 조회 DTO 참여 모임 개수 추가
> ✨ [Feat] 유저 프로필 상세 조회 DTO 가입된 모임 수 추가

- src/main/java/com/dev/moim/domain/moim/controller/MoimPostController.java
- src/main/java/com/dev/moim/domain/moim/dto/post/UpdatePostResponseDTO.java
- src/main/java/com/dev/moim/domain/moim/service/PostCommandService.java
- src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
Close #242 
- 모임 게시물 수정
- 모임 게시물 수정
> 🐛 Fix: 모임 게시물 수정

- src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
> 🐛 Fix: 중복 제거

- src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
Close #246 
- 모임 수정 api 수정
- 모임 수정 api 수정
> ♻️ Refactor: 모임 수정 api 수정

- src/main/java/com/dev/moim/domain/account/repository/UserProfileRepository.java
Close #248 
- 모임 스페이스 조회 유저 null 허용
- 모임 스페이스 조회 유저 null 허용
> ♻️ Refactor: 모임 스페이스 조회 유저 null 허용

- src/main/java/com/dev/moim/domain/moim/repository/MoimRepository.java
- 가입 완료 처리된 COMPLETE status 모임만 조회하도록 조건 추가
Close #250 
- 가입 모임 리스트 조회 쿼리 조건 추가
✔️ 18c8b5b79bd4f1e3be535184b4d00369f163d1e7 : 가입 모임 리스트 조회 쿼리 조건 추가
- 가입 완료 처리된 COMPLETE status 모임만 조회하도록 조건 추가
> 🐛 Fix: 가입 모임 리스트 조회 쿼리 조건 추가

- src/main/java/com/dev/moim/domain/account/entity/Alarm.java
- src/main/java/com/dev/moim/domain/account/service/AlarmCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/account/service/AlarmService.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/user/dto/AlarmResponseDTO.java
- src/main/java/com/dev/moim/global/firebase/service/FcmService.java
- src/main/java/com/dev/moim/global/socket/service/SocketService.java
Close #255
- 알림 id 수정
- 알림 id 수정
> MM-214 refactor: 알림 id 수정

- src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
- src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
- src/main/java/com/dev/moim/domain/moim/service/MoimCommandService.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
Close #257 
- 푸시 알림 추가 (moim & moimPost)
- 푸시 알림 추가 (moim & moimPost)
> ✨ Feature: 푸시 알림 추가 (moim & moimPost)

- src/main/java/com/dev/moim/domain/account/repository/UserRepository.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
> 🐛 Fix: 알림 수정

- src/main/java/com/dev/moim/domain/user/controller/AlarmController.java
- src/main/java/com/dev/moim/global/firebase/service/FcmService.java
> MM-218 fix: 이벤트 알림 수정

- src/main/java/com/dev/moim/domain/account/entity/enums/AlarmDetailType.java
- src/main/java/com/dev/moim/domain/moim/repository/UserPlanRepository.java
- src/main/java/com/dev/moim/domain/moim/service/impl/CalenderCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/TodoCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/user/controller/UserController.java
- src/main/java/com/dev/moim/domain/user/service/ReviewCommandService.java
- src/main/java/com/dev/moim/domain/user/service/ReviewQueryService.java
- src/main/java/com/dev/moim/domain/user/service/UserCommandService.java
- src/main/java/com/dev/moim/domain/user/service/UserQueryService.java
- src/main/java/com/dev/moim/domain/user/service/impl/ReviewCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/user/service/impl/ReviewQueryServiceImpl.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Close #259 
- 일정, todo, 멤버 후기 알림 추가
✔️ ba242be87c84bf01ff1335f28f424d6ceca9888c : 알림 추가
> ✨ Feature: 일정, todo, 멤버 후기 알림 추가

- src/main/java/com/dev/moim/domain/account/dto/JoinRequest.java
- src/main/java/com/dev/moim/global/security/filter/JwtFilter.java
> ✨ Feature: 회원가입 요청에서 fcmToken이 누락된 경우 처리

- src/main/java/com/dev/moim/domain/moim/dto/ChangeMoimLeaderRequestDTO.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
- src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
- src/main/java/com/dev/moim/global/validation/annotation/CheckOwnerValidation.java
- src/main/java/com/dev/moim/global/validation/validator/CheckOwnerValidator.java
Close #267 
- owner 권한 부여
657d77d2e059d1a6acef53813da747082871a8f9
- owner 권한 부여
> 🐛 Fix: owner 권한 부여

- src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
Close #274 
- 모임 탈퇴 수정
- 모임 탈퇴 수정
> ♻️ Refactor: 모임 탈퇴 수정

- src/main/java/com/dev/moim/global/validation/validator/TodoTargetUserValidator.java
Close #269 
- todo assignee 모임 멤버 전체 선택 시, 특정 유저 선택 못하도록 설정
✔️ 96ca7adaed6ada64b331268c93fb1cbeb5f720d0 : todo assignee 전체 선택 시 조건 추가
> 🐛 Fix: todo assignee 전체 선택 시 조건 추가

- src/main/java/com/dev/moim/domain/moim/service/impl/CalenderCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/TodoCommandServiceImpl.java
Close #277 
- deviceId가 있는 유저에게만 전송되도록 조건 추가
✔️ 33729dea0a0217c6d125b5c83297b9af57481a72 : 알림 처리 방식 변경
> 🐛 Fix: 알림 처리 방식 변경

- src/main/java/com/dev/moim/domain/moim/controller/MoimTodoController.java
- src/main/java/com/dev/moim/domain/moim/service/impl/TodoQueryServiceImpl.java
Close #278 
- 커서 시작 번호 변경
✔️ f4ba583f3e7de6a2a92342b560cb9860c85293f1 : 커서 시작 번호 변경
- 커서 시작 번호 1로 통일
✔️ 6fdb9ab9edb095aea2f3f1f3c4d1fa94950f1578 : cursor, take 검증 적용
> ✨ Feature: 커서 시작 번호 변경

- src/main/java/com/dev/moim/domain/moim/dto/task/CreateTodoDTO.java
- src/main/java/com/dev/moim/domain/moim/service/impl/TodoCommandServiceImpl.java
Close #287 
- todo 생성 DTO 마감 날짜 타입 변경
✔️ 9af2fbfd94824371864432a948422fcaa54a7acc : todo 생성 DTO 마감 날짜 타입 변경
> ✨ Feature: todo 생성 DTO 마감 날짜 타입 변경

- src/main/java/com/dev/moim/domain/moim/service/impl/TodoCommandServiceImpl.java
Close #291 
- todo 할당받았을 때 푸시 알림 메세지 변경
✔️ 031ae68541bd1f6147e56574cc6e0c17ac018230 : todo 할당받았을 때 푸시 알림 메세지 변경
> ✨ Feature: todo 할당받았을 때 푸시 알림 메세지 변경

- src/main/java/com/dev/moim/domain/moim/controller/MoimTodoController.java
- src/main/java/com/dev/moim/domain/moim/dto/task/AddTodoAssigneeDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/task/DeleteTodoAssigneeDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/task/TodoAssigneeDetailDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/task/TodoDetailDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/task/UpdateTodoDTO.java
- src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
- src/main/java/com/dev/moim/domain/moim/service/TodoCommandService.java
- src/main/java/com/dev/moim/domain/moim/service/TodoQueryService.java
- src/main/java/com/dev/moim/domain/moim/service/impl/TodoCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/TodoQueryServiceImpl.java
- src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
- src/main/java/com/dev/moim/global/validation/annotation/AddAssigneeValidation.java
- src/main/java/com/dev/moim/global/validation/annotation/DeleteAssigneeValidation.java
- src/main/java/com/dev/moim/global/validation/validator/AddAssigneeValidator.java
- src/main/java/com/dev/moim/global/validation/validator/DeleteAssigneeValidator.java
- src/main/java/com/dev/moim/global/validation/validator/TodoAssigneeStatusValidator.java
Close #291 
- 모임 todo 관련 로직 수정
✔️ f6d15a7887b55d2f5f1ec73de2fbd813970216c1 : todo assignee 제외한 모임 멤버 조회 기능 구현
✔️ 9b140e65e06a3e0f333606bd19f7b89c4168e009 : todo assignee 추가 기능 구현
✔️ a4a027d69f0aa83317ecf713a7c8a362c6e09475 : todo assignee 삭제 기능 구현
✔️ 425cab71f457b805bf5dd78f4c0aed411edf1b81 : todo 수정 로직에서 assignee 수정 제거
✔️ 963e41fadaba7e1a7ff7ec51bc988491c89549cb : todo dueDate 초 설정 변경
✔️ 828e8ca8fe23b74a0e668a8d126c56c09d026644 : todoDetailDTO moimId 추가
✔️ e83f4ba8b8762796230cd0d252a3d603e0adb79e : assigneeStatus PENDING으로 변경 가능하도록 수정
✔️ 290ed1e833bc0c55b2aff9b946ab9ebf058787fd : todo 할당받았을 때 푸시 알림 메세지 변경
✔️ d7be3b12e56f9c97acf07dfd840b98eca550630b : todo 업데이트 시 assignee status 변경
> ✨ Feature: 모임 todo 관련 로직 수정

- src/main/java/com/dev/moim/domain/moim/controller/MoimTodoController.java
- src/main/java/com/dev/moim/domain/moim/dto/todo/AddTodoAssigneeDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/todo/CreateTodoDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/todo/DeleteTodoAssigneeDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/todo/TodoAssigneeDetailDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/todo/TodoDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/todo/TodoDetailDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/todo/TodoPageDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/todo/UpdateTodoDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/todo/UpdateTodoStatusDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/todo/UpdateTodoStatusResponseDTO.java
- src/main/java/com/dev/moim/domain/moim/service/TodoCommandService.java
- src/main/java/com/dev/moim/domain/moim/service/TodoQueryService.java
- src/main/java/com/dev/moim/domain/moim/service/impl/TodoCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/TodoQueryServiceImpl.java
- src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
- src/main/java/com/dev/moim/global/validation/annotation/TodoUpdateDueDateValidation.java
- src/main/java/com/dev/moim/global/validation/validator/AddAssigneeValidator.java
- src/main/java/com/dev/moim/global/validation/validator/DeleteAssigneeValidator.java
- src/main/java/com/dev/moim/global/validation/validator/TodoAssigneeStatusValidator.java
- src/main/java/com/dev/moim/global/validation/validator/TodoTargetUserValidator.java
- src/main/java/com/dev/moim/global/validation/validator/TodoUpdateDueDateValidator.java
Close #295 
- 모임 todo API 수정
✔️ a67648937eacac9399f7ed1d8613d0c5287b4bfe : todo assignee 삭제 요청 메서드 변경
✔️ 4ea3c8d5964865b3c93c8cc46645864d8f53e918 : todo DTO 디렉토리명 변경
✔️ 98cc081d4b15b8ba81999a9c110e22ba1040bf37 : todo 마감기한 수정 제한 설정
- todo 수정 시, 마감기한을 현재 날짜보다 이전으로 수정 불가능하도록 제한 설정
> ✨ Feature: 모임 todo API 수정

- src/main/java/com/dev/moim/global/security/filter/JwtFilter.java
Close #298 
- 블랙리스트 등록 토큰 처리 버그 해결
✔️ e3a7fcaf1b64966b994dd3ae45e03d0303dbe226 : 블랙리스트 등록 토큰 처리 버그 해결
> 🐛 Fix: 블랙리스트 등록 토큰 처리 버그 해결

- src/main/java/com/dev/moim/domain/moim/repository/PlanRepository.java
- src/main/java/com/dev/moim/domain/moim/repository/UserTodoRepository.java
- src/main/java/com/dev/moim/domain/user/dto/UserDailyPlanPageDTO.java
- src/main/java/com/dev/moim/domain/user/dto/UserPlanDTO.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Close #301 
- 유저 plan 관련 수정
✔️ fe083001d3d3b07a5ded96ba38df38ca66b726c7 : 특정 날짜 (연, 월. 일) 유저 전체 일정 조회 DTO moimId 추가
✔️ 96adbadcb4e24cdcd6ebd7c39796131fed41e1d0 : 특정 월 유저 전체 일정 조회에 todo 추가
> ✨ Feature: 유저 plan 관련 수정

- src/main/java/com/dev/moim/domain/account/controller/AuthController.java
- src/main/java/com/dev/moim/domain/account/dto/InquiryDTO.java
- src/main/java/com/dev/moim/domain/account/service/AuthService.java
- src/main/java/com/dev/moim/global/email/EmailUtil.java
- src/main/java/com/dev/moim/global/error/handler/EmailException.java
Close #309 
- 유저 의견 및 문의사항 보내기 기능 구현
✔️ c35dd7df528d5233d0da04183954f2d1d8d9c668 : 유저 의견 및 문의사항 보내기 기능 구현
> ✨ Feature: 유저 의견 및 문의사항 보내기 기능 구현

- src/main/java/com/dev/moim/domain/moim/dto/post/AnnouncementRequestDTO.java
- src/main/java/com/dev/moim/domain/moim/repository/PostRepository.java
- src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
Close #305 
- 모임 게시판 목록 API
- 모임 게시판 목록 API
> ♻️ Refactor: 모임 게시판 목록 API

- src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
- src/main/java/com/dev/moim/domain/moim/controller/enums/MoimRequestRole.java
- src/main/java/com/dev/moim/domain/moim/repository/MoimRepository.java
- src/main/java/com/dev/moim/domain/moim/service/MoimQueryService.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
Close #311 
- 내가 활동 중인 모임 role 추가
- 내가 활동 중인 모임 role 추가
> ♻️ Refactor: 내가 활동 중인 모임 role 추가

- src/main/java/com/dev/moim/domain/moim/service/impl/TodoCommandServiceImpl.java
- src/main/java/com/dev/moim/global/firebase/service/FcmService.java
Close #276 
- 앱 실행 중에도 푸시 알림 뜨도록 priority 설정
✔️ c7f9a5de2b94821b560c72e95728a238f94837a7 : 앱 실행 중에도 푸시 알림 뜨도록 priority 설정
- 앱 실행 중에도 푸시 알림 뜨도록 fcmService sendNoticication 로직에서 AndroidNotification, AndroidConfig 추가 설정
- 프론트측과 테스트 진행 후, 푸시 알림을 보내는 다른 로직에서도 apnConfig, androidConfig를 적용한 로직으로 변경할 예정입니다.
> ✨ Feature: 앱 실행 중에도 푸시 알림 뜨도록 priority 설정

- src/main/java/com/dev/moim/global/firebase/service/FcmService.java
Close #316 
- 푸시 알림 priority 설정 변경
✔️ dc7c58f58f34813a45aa9825500ab847e91ac75f : 푸시 알림 priority 설정 변경
> ✨ Feature: 푸시 알림 priority 설정 변경

- src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
Close #313 
- 인원 제어 수정
- 인원 제어 수정
> ♻️ Refactor: 인원 제어 수정

- src/main/java/com/dev/moim/global/firebase/service/FcmService.java
Close #320 
- ApnsConfig에서 aps 설정 추가
✔️ c907da225174a1459ec9d3a4d977d4a04effc999 : 푸시알림 ApnsConfig aps 설정 추가
> 🐛 Fix: ApnsConfig에서 aps 설정 추가

- src/main/java/com/dev/moim/global/firebase/service/FcmService.java
> 🐛 Fix: 푸시 알림 Aps contentAvailable 설정

- src/main/java/com/dev/moim/global/firebase/service/FcmService.java
Close #325
- 푸시 알림 iOS 배지 count 제거
✔️ a08c11ab90597a829e4aeeb3b76463f333d651cf : 푸시 알림 iOS 배지 count 제거
> ✨ Feature: 푸시 알림 iOS 배지 count 제거

- src/main/java/com/dev/moim/domain/account/entity/enums/AlarmDetailType.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/moim/service/impl/PostCommandServiceImpl.java
- src/main/java/com/dev/moim/domain/user/service/impl/ReviewCommandServiceImpl.java
- src/main/java/com/dev/moim/global/firebase/service/FcmService.java
- src/main/java/com/dev/moim/global/socket/service/SocketService.java
Close #328 
- FCM 모바일 운영체제 변경
- FCM 모바일 운영체제 변경
> ♻️ Refactor: FCM 모바일 운영체제 변경

- src/main/java/com/dev/moim/global/firebase/service/FcmService.java
- src/main/java/com/dev/moim/global/scheduler/PlanScheduler.java
- src/main/java/com/dev/moim/global/scheduler/TodoScheduler.java
Close #331 
- 스케줄러 알림 포그라운드 상태에서도 오도록 안드로이드, Apns 관련 설정 추가
✔️ e43e40da72442fbe10f1954fa63aff755f9fb4b1 : 스케줄러 푸시 알림 모바일 환경 설정 추가
- todo 스케줄러
- plan 스케줄러
> ✨ Feature: 스케줄러 푸시 알림 모바일 환경 설정 추가

- src/main/java/com/dev/moim/domain/account/entity/User.java
- src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
- src/main/java/com/dev/moim/domain/moim/dto/MoimExpelRequestDTO.java
- src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
- src/main/java/com/dev/moim/domain/moim/service/MoimCommandService.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
- src/main/java/com/dev/moim/global/scheduler/UserMoimScheduler.java
Close #335 
- user 테이블 같이 삭제 추가
- user 테이블 같이 삭제 추가
> Chore: user 테이블 같이 삭제 추가

- src/main/java/com/dev/moim/domain/moim/dto/todo/TodoDTO.java
- src/main/java/com/dev/moim/domain/moim/service/impl/TodoQueryServiceImpl.java
Close #337 
- 탈퇴한 유저가 작성한 todo 조회 시 에러 해결
✔️ af85e70b051cc1d43c63d690d44f497903079bd9 : 탈퇴한 유저가 작성한 todo 조회 시 에러 해결
> 🐛 Fix: 탈퇴한 유저가 작성한 todo 조회 시 에러 해결

- src/main/resources/application.yml
Close #339 
- 운영 서버 db 반영
- 운영 서버 db 반영
> Chore: 운영 서버 db 반영

- src/main/java/com/dev/moim/global/error/ExceptionAdvice.java
Close #343 
- 필드 에러 개수에 따른 처리 로직 조건 수정
✔️ 7eb66150e6ca97eb0c4ad37dfc105c89d873f02f : 필드 에러 개수에 따른 처리 로직 조건 수정
- handleMethodArgumentNotValid 메서드에서 필드 에러가 여러 개인 경우 또는 하나의 필드에 여러 에러 메세지가 적용된 경우 MULTIPLE_FIELD_VALIDATION_ERROR 에러 메세지를 전달하도록 해야하는데, 기존에 조건이 잘못되어있어서 errors.size() == 1에서 errors.size() != 1로 조건을 수정했습니다.
> 🐛 Fix: 필드 에러 개수에 따른 처리 로직 조건 수정

- src/main/java/com/dev/moim/domain/moim/entity/Todo.java
- src/main/java/com/dev/moim/domain/moim/service/impl/TodoCommandServiceImpl.java
Close #345 
- todo 이미지를 null로 수정했을 때 처리 버그 해결
✔️ 7783a0de744fc3a863dd2442209ffba2fef25370 : todo 이미지를 null로 수정했을 때 처리 수정
> 🐛 Fix: todo 이미지를 null로 수정했을 때 처리 수정

- src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
- src/main/java/com/dev/moim/domain/moim/dto/MoimExpelRequestDTO.java
- src/main/java/com/dev/moim/domain/moim/service/MoimCommandService.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
Close #350 
- delete mapping body 수정
- delete mapping body 수정
> ♻️ Refactor: delete mapping body 수정

- src/main/java/com/dev/moim/domain/user/dto/ProfileDTO.java
- src/main/java/com/dev/moim/domain/user/dto/ProfileDetailDTO.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserQueryServiceImpl.java
Close #352
- 프로필 이미지 url null인 경우 처리
✔️ 39ec09290579fe4f606136cbb6c73006f58879f4 : 프로필 이미지 url null인 경우 처리
> 🐛 Fix: 프로필 이미지 url null인 경우 처리

- src/main/java/com/dev/moim/domain/account/entity/UserProfile.java
- src/main/java/com/dev/moim/domain/moim/entity/UserMoim.java
- src/main/java/com/dev/moim/domain/moim/repository/UserMoimRepository.java
- src/main/java/com/dev/moim/domain/user/controller/UserController.java
- src/main/java/com/dev/moim/domain/user/dto/CreateProfileDTO.java
- src/main/java/com/dev/moim/domain/user/service/UserCommandService.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserCommandServiceImpl.java
Close #
- 멀티 프로필 생성 기능 구현
✔️ 6e7a4bdebc19d1e3d4d6f327a7abb87c3040088b : 멀티 프로필 생성 기능 구현
✔️ b5e6a8f613f7ad0913cac40abab947249ac98981 : 프로필 수정 imageKey null 처리
> ✨ Feature: 멀티 프로필 생성 기능 구현

- src/main/java/com/dev/moim/domain/moim/controller/MoimCalendarController.java
- src/main/java/com/dev/moim/domain/moim/dto/calender/PlanDetailDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/calender/ScheduleCreateDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/calender/ScheduleGetDTO.java
- src/main/java/com/dev/moim/domain/moim/entity/Schedule.java
- src/main/java/com/dev/moim/domain/moim/service/impl/CalenderQueryServiceImpl.java
Close #357 
- 모임 일정 상세 스케줄 startTime 타입 변경
✔️ 62194a6d2e138ac820f2560e1235482832261e69 : 모임 일정 상세 스케줄 startTime 타입 변경
- Schedule 엔티티 startTime 타입 LocalTime으로 변경
- ScheduleCreateDTO에서 startTime 타입 변경
- ScheduleGetDTO에서 startTime 타입 변경
> 🐛 Fix: 모임 일정 상세 스케줄 startTime 타입 변경

- src/main/java/com/dev/moim/domain/moim/dto/calender/PlanDetailDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/calender/ScheduleGetDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/calender/ScheduleListDTO.java
- src/main/java/com/dev/moim/domain/moim/entity/Schedule.java
- src/main/java/com/dev/moim/domain/moim/service/impl/CalenderCommandServiceImpl.java
Close #359 
- 모임 일정 상세 스케줄 제목 컬럼명 title로 변경
✔️ 3305c94d17fd0ed70a080af72ce1ab27dd21f34f : 모임 일정 상세 스케줄 제목 컬럼명 title로 변경
- 엔티티 컬럼명 content에서 title로 변경
- 일정 관련 DTO 필드명 정리
> ✨ Feature: 모임 일정 상세 스케줄 제목 컬럼명 title로 변경

- src/main/java/com/dev/moim/domain/moim/controller/MoimController.java
- src/main/java/com/dev/moim/domain/moim/dto/MoimRoleResponse.java
- src/main/java/com/dev/moim/domain/moim/service/MoimCommandService.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimCommandServiceImpl.java
Close #365 
- 자신의 role 반환 수정
- 자신의 role 반환 수정
> ♻️ Refactor: 자신의 role 반환 수정

- src/main/java/com/dev/moim/domain/account/entity/UserProfile.java
Close #370
- 프로필 수정 버그 해결
✔️ e34da69603e5d859fb50e6df87306d427e10a9e1 : 프로필 수정 버그 해결
> 🐛 Fix: 프로필 수정 버그 해결

- src/main/java/com/dev/moim/domain/user/controller/UserController.java
- src/main/java/com/dev/moim/domain/user/dto/UpdateMoimProfileDTO.java
- src/main/java/com/dev/moim/domain/user/service/UserCommandService.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserCommandServiceImpl.java
Close #372 
- 특정 모임에서 사용할 프로필 수정 API 구현
✔️ d5ff05dd36afee09c9e9a4537a4fafdade32c968 : 특정 모임에서 사용할 프로필 수정 API 구현
> ✨ Feature: 특정 모임에서 사용할 프로필 수정 API 구현

- src/main/java/com/dev/moim/domain/account/entity/User.java
- src/main/java/com/dev/moim/domain/user/dto/UpdateUserInfoDTO.java
- src/main/java/com/dev/moim/domain/user/service/impl/UserCommandServiceImpl.java
Close #376 
- 멀티 프로필 적용 전 ver 유저 프로필 수정 DTO 필드 추가
✔️ b62aa2af9a540dd1cc46a7ab5794e953d96359b4 : 멀티 프로필 적용 전 ver 유저 프로필 수정 DTO 필드 추가
- 생년월일, 성별 필드 추가
> ✨Feature: 멀티 프로필 적용 전 ver 유저 프로필 수정 DTO 필드 추가

- src/main/java/com/dev/moim/domain/moim/dto/MoimDetailDTO.java
- src/main/java/com/dev/moim/domain/moim/service/impl/MoimQueryServiceImpl.java
Close #378 
- 모임 상세 조회 성별 조회 규칙 변환
- 모임 상세 조회 성별 조회 규칙 변환
> ♻️ Refactor: 모임 상세 조회 성별 조회 규칙 변환

- src/main/java/com/dev/moim/domain/user/dto/ProfileDetailDTO.java
Close #380 
- 유저 프로필 상세 조회 DTO 필드 추가
✔️ 778bce6d94aabe5545d001d94d6786b2141ff9c2 : 유저 프로필 상세 조회 DTO 필드 추가
- profileId, profileType, provider, gender 추가
> ✨ Feature: 유저 프로필 상세 조회 DTO 필드 추가

- src/main/java/com/dev/moim/domain/moim/dto/post/AnnouncementRequestDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/post/CreateMoimPostDTO.java
- src/main/java/com/dev/moim/domain/moim/dto/post/UpdateMoimPostDTO.java
- src/main/java/com/dev/moim/domain/moim/entity/Post.java
Close #386 
- 길이 제한 post
- 길이 제한 post
> ♻️ Refactor: 길이 제한 post

- src/main/java/com/dev/moim/domain/moim/controller/MoimTodoController.java
- src/main/java/com/dev/moim/domain/moim/dto/todo/TodoDTO.java
- src/main/java/com/dev/moim/domain/moim/repository/UserTodoRepository.java
- src/main/java/com/dev/moim/domain/moim/service/TodoQueryService.java
- src/main/java/com/dev/moim/domain/moim/service/impl/TodoQueryServiceImpl.java
Close #384 
- 특정 모임에서 할당받은 todo 리스트 조회 기능 구현
✔️ 315e98c9ea65071cfab1c5745ddd38d304cf675d : 특정 모임에서 할당받은 todo 리스트 조회 기능 구현
> ✨ Feature: 특정 모임에서 할당받은 todo 리스트 조회 기능 구현

- src/main/java/com/dev/moim/domain/account/service/AuthService.java
- src/main/java/com/dev/moim/global/common/code/status/ErrorStatus.java
- src/main/java/com/dev/moim/global/security/filter/CustomLoginFilter.java
- src/main/java/com/dev/moim/global/security/filter/CustomLogoutHandler.java
- src/main/java/com/dev/moim/global/security/filter/JwtFilter.java
- src/main/java/com/dev/moim/global/security/filter/OAuthLoginFilter.java
- src/main/java/com/dev/moim/global/security/service/OIDCService.java
Close #388 
- redis 연결 문제로 인한 에러 예외 처리 추가
✔️ cf0413f62a567935c790a30e934a1453592b0fe5 : redis 연결 에러 처리
> ✨ Feature: redis 연결 에러 처리
